---
- name: Application deployment automation
  hosts: localhost
  become: yes
  become_user: mahesh
  gather_facts: false
  tasks:
    - name: "Package spring boot application"
      shell: mvn clean package
      register:  mvn_out
      debug:
        msg: {{ mvn_out }}