---
- name: "deploy package to app server"
  hosts: tomcat_servers
  become: yes
  gather_facts: yes
  become_user: "ubuntu"
  tasks:
    - name: "Tomcat Service Status"
      command: "service tomcat status"
      register: tc_status
    - debug:
        var: tc_status.stdout_lines
    - name: "Tomcat Service Stop"
      shell: "sudo service tomcat stop"
    - name: "get current date"
      set_fact: backup_date="{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
    - name: "Create Backup"
      command: "sudo tar -cvzf /opt/tomcat/webapps/{{ backup_date }}.tar /opt/tomcat/webapps/ROOT/"
      register: create_backup_archive
    - debug:
        var: create_backup_archive.stdout_lines
    - name: "Move Backup to Tomcat Home"
      shell: "sudo mv /opt/tomcat/webapps/{{ backup_date }}.tar /home/tomcat"
    - name: "Wipe Tomcat Root"
      shell: "sudo rm -rf /opt/tomcat/webapps/ROOT/*"
    - name: "Create Temporary Directory"
      shell: "mkdir -p /tmp/WAR_FILES"
    - name: "Copy .war file from Jenkins Server"
      copy:
        src: "/var/lib/jenkins/workspace/ansible-pipeline/target/application.war"
        dest: "/tmp/WAR_FILES/"
        force: no
    - name: "Un Archive Application"
      shell: "jar -xvf /tmp/WAR_FILES/application.war"
    - name: "Remove WAR file"
      file:
        path: "/tmp/WAR_FILES/application.war"
        state: absent
    - name: "Deploy Web Application"
      shell: "sudo cp -rp /tmp/WAR_FILES/* /opt/tomcat/webapps/ROOT/"
    - name: "Tomcat Service Start"
      shell: "sudo service tomcat start"
    - name: Delete remote war file
      file:
       path: "/tmp/WAR_FILES/"
       state: absent
    - name: "Final Status Check"
      command: "service tomcat status"
      register: tc_status_final
    - debug:
        var: tc_status_final.stdout_lines